const SqlErrorCodes = {
  DUPLICATE_ENTRY: "ER_DUP_ENTRY",
  FOREIGN_KEY_CONSTRAINT_FAILS: "ER_NO_REFERENCED_ROW_2",
  SYNTAX_ERROR: "ER_PARSE_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  INVALID_TOKEN: "INVALID_TOKEN", 
};

export default SqlErrorCodes;
